<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <OutDir>$(SolutionDir)bin\$(Configuration)-$(Platform)\</OutDir>
    <IntDir>$(SolutionDir).tmp\$(Configuration)-$(Platform)\</IntDir>
    <LocalDebuggerWorkingDirectory>$(SolutionDir)bin\$(Configuration)-$(Platform)\</LocalDebuggerWorkingDirectory>
    <RunCodeAnalysis>true</RunCodeAnalysis>
    <IncludePath>$(SolutionDir)lib\glfw-3.4.bin.WIN64\include;$(SolutionDir)lib\imgui-1.91.0-docking;$(SolutionDir)lib\imgui-1.91.0-docking\backends;$(SolutionDir)lib\glm;$(SolutionDir)lib\entt-3.13.2\src;$(SolutionDir)lib\ImGuizmo-1.83;$(SolutionDir)lib\rapidjson-1.1.0;$(SolutionDir)lib\rttr-0.9.6\include;$(SolutionDir)lib\Vulkan\Include;$(SolutionDir)lib\SPIRV-Reflect-main;$(SolutionDir)lib\gli;$(SolutionDir)lib\stb_image;$(IncludePath)</IncludePath>
    <LibraryPath>$(SolutionDir)lib\glfw-3.4.bin.WIN64\lib-vc2022;$(SolutionDir)lib\rttr-0.9.6\lib;$(SolutionDir)lib\Vulkan\Lib;$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)inc;$(SolutionDir)lib;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <SDLCheck>true</SDLCheck>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <LanguageStandard_C>Default</LanguageStandard_C>
      <DebugInformationFormat>OldStyle</DebugInformationFormat>
      <WholeProgramOptimization>false</WholeProgramOptimization>
      <RuntimeTypeInfo>true</RuntimeTypeInfo>
      <UseFullPaths>false</UseFullPaths>
    </ClCompile>
    <Link>
      <SubSystem>Windows</SubSystem>
      <AdditionalDependencies>glfw3dll.lib;vulkan-1.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalOptions>/ignore:4099 %(AdditionalOptions)</AdditionalOptions>
    </Link>
    <PostBuildEvent>
      <Command>
        xcopy "$(SolutionDir)lib\glfw-3.4.bin.WIN64\lib-vc2022\glfw3.dll" "$(OutDir)" /s /r /y /q
        xcopy "$(SolutionDir)VulkanEngine\imgui.ini" "$(OutDir)" /s /r /y /q

        if $(ConfigurationName) == Debug xcopy "$(SolutionDir)lib\rttr-0.9.6\dll\rttr_core_s_d.dll" "$(OutDir)" /s /r /y /q
        if $(ConfigurationName) == Release xcopy "$(SolutionDir)lib\rttr-0.9.6\dll\rttr_core_s.dll" "$(OutDir)" /s /r /y /q

        xcopy "$(SolutionDir)Assets\Resources\*" "$(OutDir)Assets\Resources\" /s /r /y /q</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>